>P1;3J4Q
structure:3J4Q:13:D :350 :::::
-------------------------------------------------------ESVKE
FLAKAKEDFLKKWETPSQNTAQLDQFDRIKTLGTGSFGRVMLVKHKESGNHYAMKILDKQ
KVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFKDNSNLYMVMEYVAGGEMFSHLRRIGR
FSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPENLLIDQQGYIQVTDFGFAKRVKGRTWT
LCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEMAAGYPPFFADQPIQIYEKIVSGKVRF
PSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDIKNHKWFATTDWIAIYQRKVEAPFIPK
F-------------EEEIRVSIN--EKCGKEFTEF*
>P1;4AE6
structure:4AE6:12:A :318 :::::
------------------------------------------------------SSDVKE
FLAKAKEDFLKKWESPAQNTAHLDQFERIKTLGTGSFGRVMLVKHKETGNHYAMKILDKQ
KVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFKDNSNLYMVMEYVPGGEMFSHLRRIGR
FSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPENLLIDQQGYIQVTDFGFAKRVKGRTWT
LCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEMAAGYPPFFADQPIQIYEKIVSGKVRF
PSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDIKNHKWFATTDWIAIYQRKVEAPFIPK
F----------------------------------*
>P1;5X3F
structure:5X3F:107:B :455 :::::
----------KETQEASWEIFTLPNLNGRQVAAFISSLLDDPSQSANLLAEAKKLNDVQA
FLAKAKEDFLKKWETPSQNTAQLDQFDRIKTLGTGSFGRVMLVKHKESGNHYAMKILDKQ
KVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFKDNSNLYMVMEYVAGGEMFSHLRRIGR
FSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPENLLIDQQGYIQVTDFGFAKRVKGRTW-
LCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEMAAGYPPFFADQPIQIYEKIVSGKVRF
PSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDIKNHKWFATTDWIAIYQRKVEAPFIP-
-----------------------------------*
>P1;seq
sequence:seq:::::::0.00: 0.00
--------------------ME--------PPACAEAAVKDPAAR--------DHDPVDA
KISAPAADPLPR-TSSQKEGHSLQDWDTIATVGTGTFGRVNLVKEKTGRRYCALKIMSIP
DVIRLKQEQHVQNEKAVLKEINHPFLIKLLWTDHDNRFLYMLMEFVPGGELFTYLRNRGR
FSSVAAIFYATEIVCAIEYLHSKEIVYRDLKPENILLDREGHIKLTDFGFAKKLVDRTWT
LCGTPEYLAPEVIQSKGHGRAVDWWALGILIFEMLSGFPPFFDDNPFGIYQKILACKIDF
PRQLDFTSKDLIKKLLVVDRTRRLGNMKNGAEDIKRHRWFRGVEWESVPQRKLKPPIVPK
LSSDGDISNFETYPEGELDKTPSVSDEDLETFKNF*
