>P1;seq
sequence:seq:::::::0.00: 0.00
--MEPPACAEAAVKDPAARDHDPVDAKISAPAADPLP-RTSSQKEGHSLQDWDTIATVGT
GTFGRVNLVKEKTGRRYCALKIMSIPDVIRLKQEQHVQNEKAVLKEINHPFLIKLLWTDH
DNRFLYMLMEFVPGGELFTYLRNRGRFSSVAAIFYATEIVCAIEYLHSKEIVYRDLKPEN
ILLDREGHIKLTDFGFAKKLVDRTWTLCGTPEYLAPEVIQSKGHGRAVDWWALGILIFEM
LSGFPPFFDDNPFGIYQKILACKIDFPRQLDFTSKDLIKKLLVVDRTRRLGNMKNGAEDI
KRHRWFRGVEWESVPQRKLKPPIVPKLSSDGDISNFETYPEGELDKTPSVSDEDLETFKN
F*
>P1;1CTP
structure:1CTP:7:E :350 :::::
---------KK------GSEQESVKEFLAKAKEDFLKKWENPAQNTAHLDQFERIKTLGT
GSFGRVMLVKHKETGNHFAMKILDKQKVVKLKQIEHTLNEKRILQAVNFPFLVKLEYSFK
DNSNLYMVMEYVPGGEMFSHLRRIGRFSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPEN
LLIDQQGYIQVTDFGFAKRVKGRTW-LCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEM
AAGYPPFFADQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDI
KNHKWFATTDWIAIYQRKVEAPFIPK---------FDDYEEEEIRVS----EKCGKEFSE
F*
>P1;2F7E
structure:2F7E:15:E :350 :::::
-----------------------VKEFLAKAKEDFLKKWENPAQNTAHLDQFERIKTLGT
GSFGRVMLVKHMETGNHYAMKILDKQKVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFK
DNSNLYMVMEYVPGGEMFSHLRRIGRFSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPEN
LLIDQQGYIQVTDFGFAKRVKGRTWTLCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEM
AAGYPPFFADQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDI
KNHKWFATTDWIAIYQRKVEAPFIPKFKGPGDTSNFDDYEEEEIRVSIN--EKCGKEFSE
F*
>P1;3J4Q
structure:3J4Q:13:D :350 :::::
---------------------ESVKEFLAKAKEDFLKKWETPSQNTAQLDQFDRIKTLGT
GSFGRVMLVKHKESGNHYAMKILDKQKVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFK
DNSNLYMVMEYVAGGEMFSHLRRIGRFSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPEN
LLIDQQGYIQVTDFGFAKRVKGRTWTLCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEM
AAGYPPFFADQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDI
KNHKWFATTDWIAIYQRKVEAPFIPKF-------------EEEIRVSIN--EKCGKEFTE
F*
>P1;4WIH
structure:4WIH:-1:A :350 :::::
GHMGNAAAAKK------G-EQESVKEFLAKAKEEFLKKWESPSQNTAQLDHFDRIKTLGT
GSFGRVMLVKHKETGNHYAMKILDKQKVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFK
DNSNLYMVMEYVPGGEMFSHLRRIGRFSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPEN
LLIDQQGYIQVTDFGFAKRVKGRTW-LCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEM
AAGYPPFFADQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDI
KNHKWFATTDWIAIYQRKVEAPFIPKFKGPGDTSNFDDYEEEEIRV-IN--EKCGKEFTE
F*
>P1;6F14
structure:6F14:8:A :350 :::::
----------K------GSEQESVKEFLAKAKEEFLKKWESPSQNTAQLDHFDRIKTLGT
----RVMLVKHKETGNHYAMKILDKQKVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFK
DNSNLYMVMEYVPGGEMFSHLRRIGRFSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPEN
LLIDQQGYIQVTDFGFAKRVKGRTW-LCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEM
AAGYPPFFADQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDI
KNHKWFATTDWIAIYQRKVEAPFIPKFKGPGDTSNFDDYEEEEIRV-IN--EKCGKEFTE
F*
>P1;6Y05
structure:6Y05:7:A :350 :::::
---------KK------GSEQESVKEFLAKAKEEFLKKWESPSQNTAQLDHFDRIKTLGT
GSFGRVMLVKHKETGNHYAMKILDKQKVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFK
DNSNLYMVMEYVPGGEMFSHLRRIGRFSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPEN
LLIDQQGYIQVTDFGFAKRVKGRTW-LCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEM
AAGYPPFFADQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDI
KNHKWFATTDWIAIYQRKVEAPFIPKFKGPGDTSNFDDYEEEEIRV-IN--EKCGKEFTE
F*